from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from database import Base
import datetime

# ✅ USER MODEL
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


# ✅ RESUME MODEL
class Resume(Base):
    __tablename__ = "resumes"

    id = Column(Integer, primary_key=True, index=True)
    
    # 🔥 Proper foreign key relation
    user_id = Column(Integer, ForeignKey("users.id"), index=True)

    filename = Column(String, nullable=False)
    extracted_text = Column(Text)   # 👈 long text ke liye Text use karo

    # Parsed details
    name = Column(String, nullable=True)
    email = Column(String, nullable=True)
    phone = Column(String, nullable=True)
    address = Column(String, nullable=True)
    skills = Column(Text, nullable=True)  # 👈 better than String
    parsed_data = Column(Text, nullable=True) # Full JSON generated by Gemini

    created_at = Column(DateTime, default=datetime.datetime.utcnow)


# ✅ INTERVIEW HISTORY
class InterviewHistory(Base):
    __tablename__ = "interview_history"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    resume_id = Column(Integer, ForeignKey("resumes.id"), nullable=True)

    questions = Column(Text, nullable=True)  # Store JSON str of questions asked
    answers = Column(Text, nullable=True)    # Store JSON str of user answers
    per_question_feedback = Column(Text, nullable=True)  # JSON str
    
    technical_score = Column(Integer, default=0)
    communication_score = Column(Integer, default=0)
    body_language_score = Column(Integer, default=0)
    final_score = Column(Integer, default=0)
    
    final_feedback = Column(Text, nullable=True)
    body_language_feedback = Column(Text, nullable=True)
    completed_at = Column(DateTime, default=datetime.datetime.utcnow)

# ✅ HUMAN BOOKING
class HumanBooking(Base):
    __tablename__ = "human_bookings"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)

    domain = Column(String, nullable=False)
    experience_level = Column(String, nullable=False)
    preferred_date = Column(String, nullable=False)
    preferred_time = Column(String, nullable=False)
    duration = Column(String, nullable=False)
    notes = Column(Text, nullable=True)

    status = Column(String, default="Pending")
    created_at = Column(DateTime, default=datetime.datetime.utcnow)